wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707416933.165129
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.9.15
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 248
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 50
fc_layer_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.03276742976821728
optimizer:
  desc: null
  value: sgd
